name: Android CI

on:
  push:
    branches: [ "android" ]
  pull_request:
    branches: [ "android" ]

jobs:
  build: android

    runs-on: android

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
